// src/renderer/src/bridge/ChatStream.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import TranscriptRow from './TranscriptRow.vue'
import TurnGroup from './TurnGroup.vue'
import ApprovalCard from './ApprovalCard.vue'
import QuestionCard from './QuestionCard.vue'
import type { PendingApproval, PendingQuestion, ChatMessage } from './session-store'

/**
 * ChatStream — the transcript view over semantic transcript items (§2.3):
 * user content right (light bubble), assistant markdown left as plain text
 * flow (reference style — no card). Everything after a user message forms
 * that message's TURN GROUP: step rows (reasoning + tool calls) fold under
 * a single group header — "工作中 N 秒" while the turn runs, then
 * "已工作 N 秒" with a collapse chevron (collapsed by default, the answer
 * text stays visible). Auto-scrolls to the newest entry; the reference's
 * "回到底部" pill appears when the viewport is 240px+ above the tail.
 * Answerable gates (approvals/questions) render at the tail via props.
 */
const props = withDefaults(
  defineProps<{
    messages: ChatMessage[]
    /** Bumped when the trailing children change identity (e.g. gate count). */
    trailTick?: number
    /** Seconds elapsed on the running turn (present only while one runs). */
    runningSec?: number | null
    /** Measured wall-clock span of the most recently finished turn. */
    lastTurnMs?: number | null
    pendingApprovals: PendingApproval[]
    pendingQuestions: PendingQuestion[]
    activeSessionId: string | null
  }>(),
  { trailTick: 0, runningSec: null, lastTurnMs: null },
)

const emit = defineEmits<{
  approve: [pending: PendingApproval, outcome: 'allowed-once' | 'rejected']
  submitQuestion: [pending: PendingQuestion, answers: { id: string; selected: string[]; custom?: string }[]]
  cancelQuestion: [pending: PendingQuestion]
}>()

const streamEl = ref<HTMLDivElement | null>(null)
const endEl = ref<HTMLElement | null>(null)
const jumpVisible = ref(false)

watch(
  () => [props.messages, props.trailTick] as const,
  () => {
    endEl.value?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  },
)

function onScroll(): void {
  const el = streamEl.value
  if (el === null) return
  const fromBottom = el.scrollHeight - el.scrollTop - el.clientHeight
  jumpVisible.value = fromBottom > 240
}

function jumpToBottom(): void {
  streamEl.value?.scrollTo({ top: streamEl.value.scrollHeight, behavior: 'smooth' })
}

onMounted(() => {
  endEl.value?.scrollIntoView({ block: 'end' })
})

// Segment into turn groups: everything after a user message belongs to that
// message's turn. The last group carries the live clock / finished duration.
interface Segment {
  key: string
  running: boolean
  elapsedSec: number | null
  doneMs: number | null
  items: ChatMessage[]
}
const segments = computed<Segment[]>(() => {
  const out: Segment[] = []
  let group: ChatMessage[] = []
  let groupStart = 0
  props.messages.forEach((message, index) => {
    if (message.kind === 'user') {
      if (group.length > 0) {
        out.push({ key: `turn-${groupStart}`, running: false, elapsedSec: null, doneMs: null, items: group })
      }
      group = []
      out.push({ key: `user-${message.id}`, running: false, elapsedSec: null, doneMs: null, items: [message] })
      groupStart = index + 1
      return
    }
    if (group.length === 0) groupStart = index
    group.push(message)
  })
  if (group.length > 0) {
    const running = props.runningSec != null
    out.push({
      key: `turn-${groupStart}`,
      running,
      elapsedSec: running ? (props.runningSec ?? null) : null,
      doneMs: running ? null : props.lastTurnMs,
      items: group,
    })
  }
  return out
})
</script>

<template>
  <div class="chat-stream-wrap">
    <div ref="streamEl" class="chat-stream" aria-label="会话消息" @scroll="onScroll">
      <template v-for="segment in segments" :key="segment.key">
        <TranscriptRow
          v-if="segment.items.length === 1 && segment.items[0]?.kind === 'user'"
          :message="segment.items[0]"
        />
        <TurnGroup
          v-else
          :running="segment.running"
          :elapsed-sec="segment.elapsedSec"
          :done-ms="segment.doneMs"
          :items="segment.items"
        />
      </template>

      <ApprovalCard
        v-for="pending in pendingApprovals.filter((p) => p.sessionId === activeSessionId)"
        :key="pending.approvalId"
        :pending="pending"
        @answer="(outcome) => emit('approve', pending, outcome)"
      />
      <QuestionCard
        v-for="pending in pendingQuestions.filter((p) => p.sessionId === activeSessionId)"
        :key="pending.gateId"
        :pending="pending"
        @submit="(answers) => emit('submitQuestion', pending, answers)"
        @cancel="emit('cancelQuestion', pending)"
      />
      <div ref="endEl" />
    </div>
    <button
      v-if="jumpVisible"
      type="button"
      class="chat-jump"
      aria-label="滚动到底部"
      @click="jumpToBottom"
    >
      <svg viewBox="0 0 24 24" aria-hidden="true">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.8">
          <path d="m6 9 6 6 6-6" />
        </g>
      </svg>
    </button>
  </div>
</template>

// src/renderer/src/dsh/ChatStream.tsx
/**
 * ChatStream — the transcript view over semantic transcript items (§2.3):
 * user content right, assistant markdown left, reasoning + tool-call blocks
 * inline, streaming tails marked. Auto-scrolls to the newest entry.
 * `children` render at the tail (the answerable gates live there);
 * `trailTick` tells the scroller the tail changed without diffing children.
 */
import { useEffect, useRef, useState } from 'react'
import type { ReactElement, ReactNode } from 'react'
import type { ChatMessage } from './use-dsh-session'
import { Markdown } from './Markdown'

export interface ChatStreamProps {
  messages: ChatMessage[]
  /** Bumped when the trailing children change identity (e.g. gate count). */
  trailTick?: number
  children?: ReactNode
}

/** One collapsible tool-call card (running → done). */
function ToolBlock({ message }: { message: ChatMessage }): ReactElement {
  const [open, setOpen] = useState(false)
  if (message.kind !== 'tool') return <></>
  const title = message.title ?? '工具调用'
  const meta = message.status === 'running' ? '运行中' : (message.resultMeta ?? '完成')
  const expandable = message.argsText !== undefined || message.resultText !== undefined
  return (
    <div className="chat-row chat-row--assistant">
      <div className={`tool-card${message.status === 'running' ? ' tool-card--running' : ''}`}>
        <button
          type="button"
          className="tool-head"
          aria-expanded={open}
          onClick={() => {
            if (expandable) setOpen(!open)
          }}
        >
          <span className={`tool-status tool-status--${message.status}`} />
          <span className="tool-title">{title}</span>
          <span className={`tool-meta${message.status === 'running' ? ' tool-meta--running' : ''}`}>
            {meta}
          </span>
          {expandable && (
            <span className="tool-chev" aria-hidden="true">
              {open ? '▾' : '▸'}
            </span>
          )}
        </button>
        {open && (
          <div className="tool-body">
            {message.argsText !== undefined && <pre className="tool-pre">{message.argsText}</pre>}
            {message.resultText !== undefined && <pre className="tool-pre">{message.resultText}</pre>}
          </div>
        )}
      </div>
    </div>
  )
}

/** One collapsible reasoning ("thinking") card: open while streaming,
 *  collapsed once the block ends; click toggles a finished block. */
function ReasoningBlock({ message }: { message: ChatMessage }): ReactElement {
  // Hooks run unconditionally: the item kind never changes for a stable id,
  // but the early return must not sit above hook calls.
  const [toggled, setToggled] = useState<boolean | null>(null)
  if (message.kind !== 'reasoning') return <></>
  const streaming = message.streaming === true
  const open = toggled ?? streaming
  return (
    <div className="chat-row chat-row--assistant">
      <div className={`reasoning-card${streaming ? ' reasoning-card--streaming' : ''}`}>
        <button
          type="button"
          className="tool-head"
          aria-expanded={open}
          onClick={() => {
            if (!streaming) setToggled(!open)
          }}
        >
          <span className={`tool-status tool-status--${streaming ? 'running' : 'done'}`} />
          <span className="tool-title">思考过程</span>
          <span className={`tool-meta${streaming ? ' tool-meta--running' : ''}`}>
            {streaming ? '思考中' : '已完成'}
          </span>
          {!streaming && (
            <span className="tool-chev" aria-hidden="true">
              {open ? '▾' : '▸'}
            </span>
          )}
        </button>
        {open && <pre className="tool-pre reasoning-text">{message.text}</pre>}
      </div>
    </div>
  )
}

export function ChatStream({ messages, trailTick = 0, children }: ChatStreamProps): ReactElement {
  const endRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'end' })
  }, [messages, trailTick])

  return (
    <div className="chat-stream" aria-label="会话消息">
      {messages.map((message) =>
        message.kind === 'tool' ? (
          <ToolBlock key={message.id} message={message} />
        ) : message.kind === 'reasoning' ? (
          <ReasoningBlock key={message.id} message={message} />
        ) : message.kind === 'user' ? (
          <div key={message.id} className="chat-row chat-row--user">
            <div className="chat-bubble chat-bubble--user">
              {message.content.map((part, i) => (part.type === 'text' ? <span key={i}>{part.text}</span> : null))}
            </div>
          </div>
        ) : (
          <div key={message.id} className="chat-row chat-row--assistant">
            <div
              className={`chat-bubble chat-bubble--assistant${message.streaming ? ' chat-bubble--streaming' : ''}`}
            >
              {message.error !== undefined ? (
                <span className="chat-error">发送失败：{message.error}</span>
              ) : (
                <Markdown text={message.text} />
              )}
            </div>
          </div>
        ),
      )}
      {children}
      <div ref={endRef} />
    </div>
  )
}
