// src/renderer/src/components/WindowControls.tsx
import type { ReactElement } from 'react'

/**
 * Frameless-window chrome buttons (minimize / maximize / close).
 *
 * On Windows the system caption buttons are drawn by Windows itself via
 * titleBarOverlay (WinUI 3 style title bar), so nothing is rendered here.
 * Other platforms get the custom buttons.
 */
export function WindowControls(): ReactElement {
  if (window.dshDesktop.platform === 'win32') return <></>

  return (
    <div className="controls no-drag">
      <button
        className="ctl"
        title="最小化"
        aria-label="最小化"
        onClick={() => window.dshDesktop.minimize()}
      >
        <svg viewBox="0 0 12 12">
          <line x1="2" y1="6" x2="10" y2="6" />
        </svg>
      </button>
      <button
        className="ctl"
        title="最大化"
        aria-label="最大化"
        onClick={() => window.dshDesktop.maximize()}
      >
        <svg viewBox="0 0 12 12">
          <rect x="2.5" y="2.5" width="7" height="7" rx="1" />
        </svg>
      </button>
      <button
        className="ctl danger"
        title="关闭"
        aria-label="关闭"
        onClick={() => window.dshDesktop.close()}
      >
        <svg viewBox="0 0 12 12">
          <path d="M3 3l6 6M9 3l-6 6" />
        </svg>
      </button>
    </div>
  )
}

// src/uibase/WindowControls/WindowControls.vue
<script setup lang="ts">
import './WindowControls.css'

/** WindowControls emits the platform window ops; the host wires them. */
defineEmits<{
  minimize: []
  maximize: []
  close: []
}>()
</script>

<template>
  <div class="controls no-drag">
    <button class="ctl" title="最小化" aria-label="最小化" @click="$emit('minimize')">
      <svg viewBox="0 0 12 12" aria-hidden="true">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.3">
          <line x1="2" y1="6" x2="10" y2="6" />
        </g>
      </svg>
    </button>
    <button class="ctl" title="最大化" aria-label="最大化" @click="$emit('maximize')">
      <svg viewBox="0 0 12 12" aria-hidden="true">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.3">
          <rect x="2.5" y="2.5" width="7" height="7" rx="1" />
        </g>
      </svg>
    </button>
    <button class="ctl danger" title="关闭" aria-label="关闭" @click="$emit('close')">
      <svg viewBox="0 0 12 12" aria-hidden="true">
        <g fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.3">
          <path d="M3 3l6 6M9 3l-6 6" />
        </g>
      </svg>
    </button>
  </div>
</template>
